site_name: reNgine Documentation for Developers and Pentesters

# Theme
theme:
  name: material
  palette:
    scheme: default
    primary: blue
  font:
    text: Nunito Sans
    code: Roboto Mono

repo_url: https://github.com/yogeshojha/rengine

site_description: reNgine is an automated reconnaissance framework meant for information gathering during penetration testing of web applications. reNgine has customizable scan engines, which can be used to scan the websites, endpoints, and gather information.
site_author: Yogesh Ojha

copyright: Copyright &copy; 2020 reNgine

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.superfences

# Nav Bar
nav:
    - Home: 'index.md'
    - 'For Penetration Testers':
        - 'Introduction': 'pentester/install/#for-penetration-testers'
        - 'Prerequisites': 'pentester/install/#prerequisites'
        - 'Installation Instructions': '/pentester/install/#rengine-installation'
        - 'Usage': '/pentester/usage/'
        - 'Defining Scan Engines': '/pentester/scan_engine/'
        - Adding and Importing Targets: '/pentester/usage/#targets'
        - reNgine Configurations: '/pentester/usage/#configurations'
        - Wordlist: '/pentester/usage/#wordlist'
        - Notification: '/pentester/usage/#notification'
        - Initiating Scan: '/pentester/usage/#initiating-scan'
        - Scan Status: '/pentester/usage/#scan-status'
        - Scheduling Scan: '/pentester/usage/#scheduling-scan'
        - Vulnerability Scan (Beta): '/pentester/usage/#vulnerability-scan-beta'
    - For Developers:
        - 'Welcome': 'developer/index.md'
